### ISSUE TITLE
xcode 10 cycle inside grdb.swift-ios error

### ISSUE THREAD

**Issue by mheist09** [groue/GRDBObjc#5]
Hi

we are getting

           cycle inside grdb.swift-ios; building could produce unreliable results 

build errors under xcode 10, using pods

          pod 'GRDBObjc', :tag => 'v0.7', :git => 'https://github.com/groue/GRDBObjc.git', branch: 'master'
          pod 'GRDBObjcCore', :tag => 'v0.7', :git => 'https://github.com/groue/GRDBObjc.git', branch: 'master'

same issue as here, doing a clean works/pointing to GRDB 3.3.3 would fix

https://github.com/groue/GRDB.swift/issues/395

Thanks a lot for GRDB/GRDBObjc, works really well and saved us a ton of rewriting

**Comment by groue** [comment]
Hello @mheist09,

Thanks for your interest in GRDBObjc!

I suggest you update your Podfile according to the [Installation instructions](https://github.com/groue/GRDBObjc/blob/master/README.md#installation), and bring both GRDB and GRDBObjc to their latest versions. Tell me if the error is still there.

**Comment by mheist09** [comment]
Oh sorry didn't see new instructions
I didn't get newest versions:

    Using GRDB.swift (3.2.0)
    Installing GRDBObjc 0.6 (was 0.7)
    Installing GRDBObjcCore 0.6 (was 0.7)

but haven't seen the error in a couple of different builds from scratch. 

I also switched our project back to swift 4 instead of 4.2, not sure if that mattered but we didn't need 4.2 anyway.

thanks for help

**Comment by groue** [comment]
All right, it looks like you're good. Happy GRDB!
